version: '3'

services:
        database:
                image: mariadb
                restart: always
                volumes:
                        - sql_storage:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: sqlpass
                        MYSQL_USER: akshat
                        MYSQL_PASSWORD: userpass
                        MYSQL_DATABASE: wp_db

        wordpressos:
                image: wordpress
                restart: always
                depends_on:
                        - database
                ports:
                        - 8080:80
                volumes:
                        - wp_storage:/var/www/html
                environment:
                        WORDPRESS_DB_HOST: database
                        WORDPRESS_DB_USER: akshat
                        WORDPRESS_DB_PASSWORD: userpass
                        WORDPRESS_DB_NAME: wp_db

volumes:
        sql_storage:
        wp_storage:
